on: push
defaults:
  run:
    working-directory: node
jobs:
  gcp:
    # based on https://github.com/davidkhala/gcp-collection/blob/main/.github/workflows/wif.yaml
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - uses: actions/checkout@main
      - uses: google-github-actions/auth@v2
        with:
          service_account: 'cloud-region@freetier-only.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/207043494928/locations/global/workloadIdentityPools/github/providers/github-action'
      - uses: actions/setup-node@main
      - run: npm install
      - run: npx mocha test/gcp.js
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: regions.csv
  aws:
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: aws-actions/configure-aws-credentials@main
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1
      - run: npm install
      - run: npx mocha test/aws.js
