name: Google Cloud
on: push
jobs:
  node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node
    steps:
      - run: npm i
      - run: npm test
        env:
          private_key: ${{secrets.GSERVICEACCOUNT_PRIVATE_KEY}}
