name: Google Cloud
on: push
jobs:
  node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-node@latest
        with:
          node-version: 14.x
      - run: npm install
      - run: npm test
        env:
          private_key: ${{ secrets.GSERVICEACCOUNT_PRIVATE_KEY }}
